<a href="https://colab.research.google.com/github/bongkyunSON/Pytorch/blob/main/PyTorch_Useful_Methods_221221.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Useful Methods

In [1]:
import torch

### expand: copy the given tensor and concat those at desired dimension.

In [2]:
x = torch.FloatTensor([[[1, 2]],
                       [[3, 4]]])
print(x.size())

torch.Size([2, 1, 2])


In [3]:
y = x.expand(*[2, 3, 2])

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


#### Implement expand with cat.

In [4]:
y = torch.cat([x, x, x], dim=1)

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


### randperm: Random Permutation

In [5]:
x = torch.randperm(10)

print(x)
print(x.size())

tensor([0, 2, 1, 6, 4, 8, 7, 9, 3, 5])
torch.Size([10])


### argmax: Return index of maximum values

In [26]:
x = torch.randperm(3**3).reshape(3, 3, -1)

print(x)
print(x.size())

tensor([[[11, 21,  1],
         [ 7, 23, 25],
         [19, 20, 13]],

        [[ 9,  0, 26],
         [22, 24, 12],
         [ 2, 15, 10]],

        [[18,  8,  4],
         [17,  5,  3],
         [16,  6, 14]]])
torch.Size([3, 3, 3])


In [27]:
y = x.argmax(dim=0)

print(y)
print(y.size())

tensor([[2, 0, 1],
        [1, 1, 0],
        [0, 0, 2]])
torch.Size([3, 3])


In [28]:
y = x.argmax(dim=1)

print(y)
print(y.size())

tensor([[2, 1, 1],
        [1, 1, 0],
        [0, 0, 2]])
torch.Size([3, 3])


In [29]:
y = x.argmax(dim=-1)

print(y)
print(y.size())

tensor([[1, 2, 1],
        [2, 1, 1],
        [0, 0, 0]])
torch.Size([3, 3])


### topk: Return tuple of top-k values and indices.

In [30]:
values, indices = torch.topk(x, k=1, dim=-1)

print(values.size())
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


Note that topk didn't reduce the dimension, even in $k=1$ case.

In [31]:
print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[21, 25, 20],
        [26, 24, 15],
        [18, 17, 16]])
tensor([[1, 2, 1],
        [2, 1, 1],
        [0, 0, 0]])


In [32]:
print(x.argmax(dim=-1) == indices.squeeze(-1))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [33]:
_, indices = torch.topk(x, k=2, dim=-1)
print(indices.size())

print(x.argmax(dim=-1) == indices[:, :, 0])

torch.Size([3, 3, 2])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Sort by using topk

In [34]:
target_dim = -1
values, indices = torch.topk(x,
                             k=x.size(target_dim),
                             largest=True)

print(values)

tensor([[[21, 11,  1],
         [25, 23,  7],
         [20, 19, 13]],

        [[26,  9,  0],
         [24, 22, 12],
         [15, 10,  2]],

        [[18,  8,  4],
         [17,  5,  3],
         [16, 14,  6]]])


### Topk by using sort

In [35]:
k=1
values, indices = torch.sort(x, dim=-1, descending=True)
values, indices = values[:, :, :k], indices[:, :, :k]

print(values.squeeze(-1))
print(indices.squeeze(-1))

tensor([[21, 25, 20],
        [26, 24, 15],
        [18, 17, 16]])
tensor([[1, 2, 1],
        [2, 1, 1],
        [0, 0, 0]])


### masked_fill: fill the value if element of mask is True.

In [36]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3, -1)

print(x)
print(x.size())

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])


In [37]:
mask = x > 4

print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [38]:
y = x.masked_fill(mask, value=-1)

print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


### Ones and Zeros

In [39]:
print(torch.ones(2, 3))
print(torch.zeros(2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [40]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


In [41]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
