<a href="https://colab.research.google.com/github/bongkyunSON/Pytorch/blob/main/Pytorch_Gradient_Descent_221222.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gradient Descent

In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [3]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.

x

tensor([[0.1922, 0.8123, 0.5414],
        [0.2703, 0.5504, 0.5463],
        [0.2826, 0.2221, 0.7209]], requires_grad=True)

In [4]:
loss = F.mse_loss(x, target)

loss

tensor(0.1116, grad_fn=<MseLossBackward0>)

In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    
    loss.backward() # Calculate gradients.

    x = x - learning_rate * x.grad
    
    # You don't need to aware this now.
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 6.7496e-02
tensor([[0.1717, 0.6762, 0.4878],
        [0.2991, 0.5392, 0.5582],
        [0.3754, 0.3505, 0.7607]], requires_grad=True)
2-th Loss: 4.0831e-02
tensor([[0.1558, 0.5704, 0.4460],
        [0.3215, 0.5305, 0.5675],
        [0.4475, 0.4504, 0.7917]], requires_grad=True)
3-th Loss: 2.4700e-02
tensor([[0.1434, 0.4881, 0.4136],
        [0.3390, 0.5237, 0.5747],
        [0.5036, 0.5281, 0.8157]], requires_grad=True)
4-th Loss: 1.4942e-02
tensor([[0.1337, 0.4241, 0.3884],
        [0.3525, 0.5184, 0.5803],
        [0.5473, 0.5885, 0.8345]], requires_grad=True)
5-th Loss: 9.0390e-03
tensor([[0.1262, 0.3743, 0.3687],
        [0.3631, 0.5143, 0.5847],
        [0.5812, 0.6355, 0.8490]], requires_grad=True)
6-th Loss: 5.4680e-03
tensor([[0.1204, 0.3355, 0.3534],
        [0.3713, 0.5112, 0.5881],
        [0.6076, 0.6721, 0.8604]], requires_grad=True)
7-th Loss: 3.3078e-03
tensor([[0.1159, 0.3054, 0.3416],
        [0.3777, 0.5087, 0.5907],
        [0.6281, 0.7005, 0.8692]], requi